# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.7

before_script:
  - pip install -r requirements.txt
  - pip install .

pylint:
  script:
    - pylint **/*.py

pytest:
  script:
    - python -m pytest -v --junitxml=report.xml
  artifacts:
    reports:
      junit: report.xml
